### PR TITLE
Fetch missing media files

### LINKED ISSUE #107: Missing data for certain PDFs
I'm seeing some broken PDF links due to missing data. To reproduce:

- convert res-18-006-calculus-revisited-single-variable-calculus-fall-2010. You should see `Could not load binary data for file df95386a043ade9c186c403e109240de_MITRES_18_006_supp_notes.pdf in json file 140.json for course res-18-006-calculus-revisited-single-variable-calculus-fall-2010` and other similar error messages.
 - Go to `courses/res-18-006-calculus-revisited-single-variable-calculus-fall-2010/sections/study-materials/` on your local instance. You should see a "Supplementary notes" link toward the top. The URL shows a link to a PDF file but the link is broken.
 - There is a working link on the legacy site: https://ocw.mit.edu/resources/res-18-006-calculus-revisited-single-variable-calculus-fall-2010/study-materials/

### PR DESCRIPTION
**Pull request by noisecapella**
#### What are the relevant tickets?
Fixes #107 

#### What's this PR do?
Fetches foreign media files for published courses if the base64 content is not present

#### How should this be manually tested?
Convert course `9-17-systems-neuroscience-lab-spring-2013`, then convert the parsed JSON to markdown for hugo. Go to http://localhost:3000/courses/9-17-systems-neuroscience-lab-spring-2013/sections/assignments/ and click on the "Project 3 data and files (ZIP)" link. You should be downloading a valid ZIP file.

If you do the same on the current production instance you will get a 404: http://ocwnext.odl.mit.edu/courses/9-17-systems-neuroscience-lab-spring-2013/sections/assignments/

### CODE REVIEW

**Review by mbertrand — COMMENTED** [review]
The code looks fine and the zip files download and are valid. However, I noticed that the "MATLAB Project 3" zip file contains the same content as "MATLAB Project 1".  This is not the case on the original site - https://ocw.mit.edu/courses/brain-and-cognitive-sciences/9-17-systems-neuroscience-lab-spring-2013/assignments/

I'm guessing this is a bug with the json data that's being parsed (wrong url), not the parser itself?

**Comment by noisecapella** [comment]
Oh, good catch. I'll investigate

**Comment by noisecapella** [comment]
@mbertrand I'm not sure what was going on there. I verified that the Project3 zip was a duplicate of the Project1 zip. However I ran `parse_all` on the course with a code change to set `upload_to_s3=True` and now I see the correct file for the Project3 zip

**Review by mbertrand — APPROVED** [review]
👍

**Pull request merged**
