### PR TITLE
Add option to upload master json to s3 in parse_all function

### LINKED ISSUE #75: Batch upload master json files to S3
It would be convenient to batch regenerate all master JSON files and upload them to S3 without having to use the open-discussions management command, which takes hours because it also has to download all the original plone files and upload all the course content files.

Tweak the `parse_all` function so that it can optionally upload the master JSON files (for published courses only) to S3.

### PR DESCRIPTION
**Pull request by mbertrand**
#### What are the relevant tickets?
Closes #75 

#### What's this PR do?
Adds a `upload_master_json` boolean keyword argument to `parse_all`.  If this is `True`, and the `s3_links` argument is True, and the course is published (code has been copied over from open to determine this), then the master JSON file will be uploaded to S3.  

#### How should this be manually tested?
Before running:
```
export export AWS_ACCESS_KEY_ID=<value for CI>
export AWS_SECRET_ACCESS_KEY=<value for CI>
```

Then in a shell:
```python
from ocw_data_parser.utils import *
bucket_name="open-learning-course-data-ci"
parse_all(
    "raw", 
    "output", 
    s3_bucket=bucket_name,
    s3_links=True,
    overwrite=True,
    beautify_master_json=True,
    upload_master_json=True
)
```

Then check to see that the master JSON in S3 is recent and matches what was written to the output directory:
```
import boto3
import json

s3 = boto3.resource(
    "s3",
    aws_access_key_id=os.environ["AWS_ACCESS_KEY_ID"], 
    aws_secret_access_key=os.environ["AWS_SECRET_ACCESS_KEY"]
)
# Assuming the course processed was cms-611j-creating-video-games-fall-2014
obj = s3.Object(
    bucket_name, 
    'cms-611j-creating-video-games-fall-2014/407b4d7bd6da663d702c00152b0195fd_master.json'
)

obj.last_modified

obj.download_file('output2/s3.json')

with open("output2/cms-611j-creating-video-games-fall-2014/master/master.json") as inf:
    a = json.load(inf)
with open("output2/s3.json") as inf:
    b = json.load(inf)
json.dumps(a, sort_keys=True) == json.dumps(b, sort_keys=True)
```

#### Where should the reviewer start?
(Optional)

#### Any background context you want to provide?
(Optional)

### CODE REVIEW

**Comment by gumaerc** [comment]
So it looks like this is failing codecov because of some unnecessary code that I was actually refactoring out in [this](https://github.com/mitodl/ocw-data-parser/pull/78) PR.  That shouldn't hold this back.  I'll do a proper review, then when this gets merged I can rebase my PR and the coverage should be fine.

**Comment by gumaerc** [comment]
To clarify a bit, the "master" folder being created just to put the master json file in it was created back before we started the hugo project.  `static_html_generator` was still being used to output a static html version of the site manually, and it was needed for organization.  It's no longer really necessary and the exported files should follow the bucket structure.

**Comment by gumaerc** [comment]
@mbertrand - I've been testing this today, and was able to run the entire course load against CI without issue.  The JSON updates on S3 and matches the output.  The code looks good and everything functions as expected, but there's one question floating around in my head.  `parse_all` is not designed to work directly against the bucket structure of `ocw-content-storage`, rather it is more of a "flattened" structure where it can iterate a `courses.json` file like the ones used in `ocw-to-hugo` and `hugo-course-publisher` and download those courses to a folder.  Maybe this should be done in a separate PR, but I think `OCWDownloader` should be modified to save the data in the original bucket structure.  This way, if you're a dev working with a set of example courses or just need to test out a couple specific ones, you can use a courses.json file but you can also just use an `aws s3 sync` to sync the whole bucket and parse it.  If this was done and `parse_all` was set up to iterate the "stock" bucket structure of `ocw-content-storage` the same way `OCWDownloader` does it, then we could more easily implement setting up a command to regenerate all master json on the build server I think.  What are your thoughts?

**Comment by mbertrand** [comment]
@gumaerc `OCWDownloader` seems to create separate folders for each course, with a `0` subfolder under that, and then the individual JSON files for that course.  I think what's different compared to the s3 bucket is the `PROD/<department>/<course_number>/<semester>` prefix, is that what you are referring to?  I can make a new issue for that and start on a separate PR unless you would like to work on it.

**Comment by gumaerc** [comment]
@mbertrand Yea, sounds good.  I think the reason I flattened the directory structure like that was because the department / course numbers in the course id string didn't quite match the `ocw-content-storage` names for those on the folders.  Either way, we should be able to make it work with the stock bucket structure.  If you don't have bandwidth I can take it, but otherwise feel free.

**Review by gumaerc — APPROVED** [review]
👍

**Pull request merged**
